# Generated by Django 5.2.1 on 2025-12-11 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Materia')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de la Materia')),
                ('semestre', models.IntegerField(choices=[(1, '1er Semestre'), (2, '2do Semestre'), (3, '3er Semestre'), (4, '4to Semestre'), (5, '5to Semestre'), (6, '6to Semestre'), (7, '7mo Semestre'), (8, '8vo Semestre'), (9, '9no Semestre'), (10, '10mo Semestre')], verbose_name='Semestre Actual')),
                ('profesor', models.CharField(max_length=100, verbose_name='Nombre del Profesor')),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Créditos')),
                ('dia_clase', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3, verbose_name='Día de Clase')),
                ('horario', models.CharField(choices=[('M', 'Matutino (7:00-12:00)'), ('V', 'Vespertino (12:00-17:00)'), ('N', 'Nocturno (17:00-22:00)')], max_length=1, verbose_name='Horario')),
                ('dificultad', models.IntegerField(choices=[(1, 'Muy Fácil'), (2, 'Fácil'), (3, 'Moderada'), (4, 'Difícil'), (5, 'Muy Difícil')], verbose_name='Nivel de Dificultad')),
                ('comentarios', models.TextField(verbose_name='Comentarios sobre la Materia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activa', models.BooleanField(default=True, verbose_name='Materia Activa')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['semestre', 'nombre'],
            },
        ),
    ]
